"""markdown

Revision ID: 66cee08078cc
Revises: 52895c0a02db
Create Date: 2016-06-12 10:40:42.583121

"""

# revision identifiers, used by Alembic.
revision = '66cee08078cc'
down_revision = '52895c0a02db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
