"""initial

Revision ID: de10f094830a
Revises: None
Create Date: 2016-06-18 16:28:50.854915

"""

# revision identifiers, used by Alembic.
revision = 'de10f094830a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
